#! /bin/sh

test ­n "$1" && param1=$1
test ­n "$2" && param2=$2
test ­n "$3" && param3=$3
test ­n "$4" && param4=$4
echo "1º resultado do teste:${param1­rs} com param1 = $param1”
echo "2º resultado do teste:${param2=pa} com param2 = $param2”
echo "3º resultado do teste:${param3+to} com param3 = $param3
echo  "4º  resultado   do teste:${param4?Quarto   parâmetro  não  iniciado}
com param4 =  $param4”
